spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mariadb://localhost:33060/video_chat
    username: root
    password: qwer
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

server:
  port: 8080